import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getAuth, signInWithEmailAndPassword, GoogleAuthProvider, signInWithPopup, sendPasswordResetEmail, RecaptchaVerifier, signInWithPhoneNumber, signInAnonymously } from 'firebase/auth';
import app from '../firebase';
import api from '../api/client';
import { useAuth } from '../context/AuthContext';
import ThemeToggle from '../components/ThemeToggle';
import { ensureE2E } from '../crypto/e2e';

function GoogleLogo(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#EA4335" d="M21.2 12.22c0-.67-.06-1.33-.18-1.96H12v3.71h5.16a4.42 4.42 0 0 1-1.91 2.9v2.4h3.1c1.82-1.68 2.85-4.14 2.85-7.05Z"/><path fill="#4285F4" d="M12 21.6c2.58 0 4.75-.85 6.33-2.32l-3.1-2.4c-.86.58-1.96.93-3.23.93-2.49 0-4.6-1.68-5.36-3.94H3.43v2.48A9.57 9.57 0 0 0 12 21.6Z"/><path fill="#FBBC05" d="M6.64 13.87A5.7 5.7 0 0 1 6.34 12c0-.65.11-1.28.3-1.87V7.65H3.43A9.6 9.6 0 0 0 2.4 12c0 1.55.37 3.02 1.03 4.35l3.21-2.48Z"/><path fill="#34A853" d="M12 6.19c1.4 0 2.66.48 3.65 1.43l2.74-2.74C16.75 3.28 14.58 2.4 12 2.4a9.57 9.57 0 0 0-8.57 5.25l3.21 2.48C7.4 7.87 9.51 6.19 12 6.19Z"/></svg>}
function MailLogo(){return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2.5" fill="none" stroke="currentColor" strokeWidth="1.7"/><path d="m4.5 7 7.5 6 7.5-6" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round"/></svg>}
function PhoneLogo(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.2 3.4 9.6 3c.7-.12 1.2.3 1.38.92l.77 2.72c.14.5-.02 1.04-.42 1.37L9.9 9.22a14.7 14.7 0 0 0 4.88 4.88l1.21-1.43c.34-.4.87-.56 1.38-.42l2.72.77c.62.18 1.04.69.92 1.38l-.4 2.4c-.12.73-.75 1.2-1.47 1.2C11.14 18 6 12.86 6 6.86c0-.72.47-1.35 1.2-1.47Z" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function GuestLogo(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.1" fill="none" stroke="currentColor" strokeWidth="1.6"/><path d="M5.5 19c.9-3.1 3-4.7 6.5-4.7s5.6 1.6 6.5 4.7" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round"/></svg>}
const PROVIDERS=[{id:'email',label:'Correo',icon:MailLogo},{id:'google',label:'Google',icon:GoogleLogo},{id:'phone',label:'Teléfono',icon:PhoneLogo},{id:'guest',label:'Invitado',icon:GuestLogo}];

export default function Login(){
  const [method,setMethod]=useState('email'); const [mode,setMode]=useState('login'); const [bootstrapAvailable,setBootstrapAvailable]=useState(false); const [nombre,setNombre]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [phone,setPhone]=useState(''); const [smsCode,setSmsCode]=useState(''); const [guestId,setGuestId]=useState(''); const [confirmation,setConfirmation]=useState(null); const [showPassword,setShowPassword]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [loading,setLoading]=useState(false); const recaptcha=useRef(null); const {refreshUser}=useAuth(); const navigate=useNavigate();
  useEffect(()=>{api.get('/auth/bootstrap-status').then(r=>setBootstrapAvailable(Boolean(r.data?.available))).catch(()=>setBootstrapAvailable(false)); return()=>{if(window.__sinergiaRecaptcha){try{window.__sinergiaRecaptcha.clear()}catch{} window.__sinergiaRecaptcha=null;}}},[]);
  async function finishLogin(currentPassword=''){const sessionUser=await refreshUser(); if(currentPassword){try{await ensureE2E(currentPassword,api)}catch(e){console.warn('E2E no desbloqueado:',e)}} window.dispatchEvent(new CustomEvent('sinergia:companion',{detail:{action:'login',message:'Sesión iniciada.'}})); const onlyAccounting=sessionUser?.role!=='ADMIN'&&sessionUser?.areas?.length===1&&sessionUser.areas[0]==='CONTABILIDAD'; navigate(onlyAccounting?'/contabilidad':'/');}
  function clearState(){setError('');setSuccess('');setConfirmation(null);setSmsCode('');}
  function chooseMethod(next){clearState();setMode('login');setMethod(next)}
  function openBootstrap(){clearState();setMode('bootstrap');setMethod('email')}
  async function submit(e){e.preventDefault();clearState();setLoading(true);try{const auth=getAuth(app); if(mode==='bootstrap'){try{const credential=await signInWithEmailAndPassword(auth,email.trim().toLowerCase(),password);const idToken=await credential.user.getIdToken(true);await api.post('/auth/bootstrap-existing',{idToken,nombre:nombre.trim()||credential.user.displayName||email.trim().split('@')[0]});}catch(fbErr){if(fbErr?.response?.status===409)throw fbErr;const code=fbErr?.code;if(code==='auth/user-not-found'||code==='auth/invalid-credential'||code==='auth/invalid-login-credentials'){await api.post('/auth/bootstrap-admin',{nombre,email,password});await signInWithEmailAndPassword(auth,email.trim().toLowerCase(),password)}else throw fbErr;}}else{await signInWithEmailAndPassword(auth,email.trim().toLowerCase(),password)} await finishLogin(password);}catch(err){setError(serverMessage(err))}finally{setLoading(false)}}
  async function loginGoogle(){clearState();setLoading(true);try{await signInWithPopup(getAuth(app),new GoogleAuthProvider());await finishLogin('')}catch(err){setError(err?.code==='auth/popup-closed-by-user'?'La ventana de Google se cerró.':serverMessage(err,'No se pudo iniciar sesión con Google.'))}finally{setLoading(false)}}
  async function beginPhone(){clearState();if(!phone.trim()){setError('Escribe tu número con código de país.');return}setLoading(true);try{const auth=getAuth(app);if(window.__sinergiaRecaptcha){try{window.__sinergiaRecaptcha.clear()}catch{}}window.__sinergiaRecaptcha=new RecaptchaVerifier(auth,'recaptcha-container',{size:'invisible'});const result=await signInWithPhoneNumber(auth,phone.trim(),window.__sinergiaRecaptcha);setConfirmation(result);setSuccess('Código enviado por SMS.')}catch(err){setError(err?.code==='auth/invalid-phone-number'?'El número de teléfono no es válido.':serverMessage(err,'No pudimos enviar el código SMS.'))}finally{setLoading(false)}}
  async function verifyPhone(){if(!confirmation||!smsCode.trim()){setError('Escribe el código SMS.');return}setLoading(true);clearState();try{await confirmation.confirm(smsCode.trim());await finishLogin('')}catch(err){setError(err?.code==='auth/invalid-verification-code'?'El código SMS no es correcto.':serverMessage(err,'No pudimos verificar el código.'))}finally{setLoading(false)}}
  async function loginGuest(){clearState();if(!guestId.trim()){setError('Escribe el ID de invitado que te entregó el administrador.');return}setLoading(true);try{const credential=await signInAnonymously(getAuth(app));const idToken=await credential.user.getIdToken(true);await api.post('/auth/guest-session',{idToken,guestId:guestId.trim().toUpperCase()});await finishLogin('')}catch(err){setError(serverMessage(err,'No se pudo vincular el acceso de invitado.'));try{await getAuth(app).signOut()}catch{}}finally{setLoading(false)}}
  async function recover(){setError('');setSuccess('');if(!email.trim()){setError('Escribe tu correo electrónico primero.');return}setLoading(true);try{await sendPasswordResetEmail(getAuth(app),email.trim().toLowerCase());setSuccess('Te enviamos el enlace para restablecer tu contraseña.')}catch(err){setError(err?.code==='auth/user-not-found'?'No encontramos una cuenta con ese correo.':'No pudimos enviar el correo. Verifica la dirección.')}finally{setLoading(false)}}
  const bootstrap=mode==='bootstrap';
  return <main className="login-v9"><div className="login-v9-grid" aria-hidden="true"/><header className="login-v9-top"><div className="login-v9-brand"><span className="login-v9-logo">S</span><div><strong>SINERGIA</strong><small>SOFTWARE</small></div></div><ThemeToggle/></header><section className="login-v9-wrap"><div className="login-v9-card"><div className="login-v9-brandline"><span className="login-v9-dot"/><span>{bootstrap?'PRIMER ADMINISTRADOR':'ACCESO'}</span></div><h1>{bootstrap?'Crear administrador':'Bienvenido'}</h1>{bootstrap?<p className="login-v9-sub">Configura la primera cuenta del sistema.</p>:null}
      {!bootstrap&&<div className="login-v9-provider-grid">{PROVIDERS.map(({id,label,icon:Icon})=><button key={id} type="button" className={`login-v9-provider ${method===id?'active':''}`} onClick={()=>chooseMethod(id)}><span className="login-v9-provider-icon"><Icon/></span><span>{label}</span></button>)}</div>}
      {bootstrap&&<button type="button" className="login-v9-back" onClick={()=>{clearState();setMode('login')}}>← Volver al acceso</button>}
      {((!bootstrap&&method==='email')||bootstrap)&&<form onSubmit={submit} className="login-v9-form">{bootstrap&&<Field label="Nombre" value={nombre} onChange={setNombre} placeholder="Nombre completo" autoComplete="name"/>}<Field label="Correo electrónico" value={email} onChange={setEmail} placeholder="nombre@empresa.com" type="email" autoComplete="email"/><Field label="Contraseña" value={password} onChange={setPassword} placeholder="Mínimo 8 caracteres" type={showPassword?'text':'password'} autoComplete={bootstrap?'new-password':'current-password'} right={<button type="button" onClick={()=>setShowPassword(v=>!v)}>{showPassword?'Ocultar':'Mostrar'}</button>}/>{!bootstrap&&<div className="login-v9-forgot"><button type="button" onClick={recover}>¿Olvidaste tu contraseña?</button></div>}<Feedback error={error} success={success}/><button className="login-v9-submit" disabled={loading}>{loading?(bootstrap?'Creando…':'Entrando…'):(bootstrap?'Crear administrador':'Iniciar sesión')}<span>→</span></button></form>}
      {!bootstrap&&method==='google'&&<Alt title="Google" icon={<GoogleLogo/>} text="Usa tu cuenta Google vinculada a Sinergia." error={error} success={success}><button className="login-v9-submit" disabled={loading} onClick={loginGoogle}>Continuar con Google <span>→</span></button></Alt>}
      {!bootstrap&&method==='phone'&&<Alt title={confirmation?'Código SMS':'Teléfono'} icon={<PhoneLogo/>} text={confirmation?'Escribe el código que recibiste.':'Accede con el número asociado a tu cuenta.'} error={error} success={success}><Field label={confirmation?'Código SMS':'Número de teléfono'} value={confirmation?smsCode:phone} onChange={confirmation?setSmsCode:setPhone} placeholder={confirmation?'123456':'+1 809 555 1234'} inputMode={confirmation?'numeric':'tel'} autoComplete={confirmation?'one-time-code':'tel'}/><button className="login-v9-submit" disabled={loading} onClick={confirmation?verifyPhone:beginPhone}>{loading?(confirmation?'Verificando…':'Enviando…'):(confirmation?'Verificar código':'Enviar código')}<span>→</span></button></Alt>}
      {!bootstrap&&method==='guest'&&<Alt title="Invitado" icon={<GuestLogo/>} text="Necesitas el ID de invitado que te asignó un administrador o responsable del proyecto." error={error} success={success}><Field label="ID de invitado" value={guestId} onChange={setGuestId} placeholder="INV-ABC123" autoComplete="off"/><button className="login-v9-submit" disabled={loading} onClick={loginGuest}>{loading?'Vinculando…':'Entrar como invitado'}<span>→</span></button></Alt>}
      {!bootstrap&&bootstrapAvailable&&<div className="login-v9-first"><button type="button" onClick={openBootstrap}>Crear primera cuenta administrativa</button></div>}
      {bootstrap&&<div className="login-v9-first"><button type="button" onClick={()=>{clearState();setMode('login')}}>Volver al acceso</button></div>}
      <div id="recaptcha-container" ref={recaptcha}/></div></section><footer className="login-v9-footer">SINERGIA SOFTWARE · V0.5</footer></main>
}
function Alt({title,icon,text,error,success,children}){return <div className="login-v9-alt"><div className="login-v9-alt-head"><span className="login-v9-alt-icon">{icon}</span><div><h2>{title}</h2><p>{text}</p></div></div>{children&&<div className="login-v9-alt-body">{children}</div>}<Feedback error={error} success={success}/></div>}
function Field({label,type='text',value,onChange,placeholder,autoComplete,right,inputMode}){return <label className="login-v9-field"><span>{label}</span><div><input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} autoComplete={autoComplete} required inputMode={inputMode} minLength={type==='password'?8:undefined}/>{right&&<span className="login-v9-field-action">{right}</span>}</div></label>}
function Feedback({error,success}){if(!error&&!success)return null;return <div className={`login-v9-feedback ${error?'error':'success'}`}><span>{error?'!':'✓'}</span><p>{error||success}</p></div>}
function serverMessage(err,fallback='No pudimos completar el acceso.') { const apiError=err?.response?.data; if(apiError?.error) return apiError.error; const code=err?.code||''; const map={'auth/invalid-credential':'Correo o contraseña incorrectos.','auth/user-not-found':'No encontramos esa cuenta.','auth/wrong-password':'Correo o contraseña incorrectos.','auth/too-many-requests':'Demasiados intentos. Espera unos minutos.','auth/popup-blocked':'El navegador bloqueó la ventana de acceso.','auth/invalid-phone-number':'Número de teléfono no válido.','auth/operation-not-allowed':'Este método de acceso no está habilitado.','FIREBASE_TOKEN_VERIFY_FAILED':'El backend no pudo verificar tu sesión de Firebase. Revisa la credencial de Firebase Admin y que pertenezca al proyecto sinergia-interactiva.','FIREBASE_SERVICE_ACCOUNT_MISSING':'Falta la credencial de Firebase Admin en el backend.','FIREBASE_SERVICE_ACCOUNT_INVALID':'La credencial de Firebase Admin del backend está incompleta.','USER_NOT_REGISTERED':'La cuenta está autenticada en Firebase, pero no existe un usuario activo en Sinergia.'}; return map[code]||fallback; }
